apiVersion: 1

datasources:
  - name: Prediction PostgreSQL
    uid: prediction-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: predictions
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
